services:

  postgresql:
    image: "postgres:16-alpine"
    container_name: postgresql
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env


volumes:
  postgres_data: {}