services:

  backend:
    build: ./
    container_name: backend_starnavi
    restart: always
    ports:
      - "8005:8000"
    volumes:
      - ./migrations:/project/migrations
      - ./src:/project/src
      - ./main.py:/project/main.py
    depends_on:
      - postgresql
    env_file:
      - .env


  postgresql:
    image: "postgres:16-alpine"
    container_name: postgresql_starnavi
    restart: always
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env


volumes:
  postgres_db_data: {}