"""Added is_blocked in model Post

Revision ID: 04e7646e7e6c
Revises: 2a529c141db6
Create Date: 2024-10-18 23:03:03.243422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04e7646e7e6c'
down_revision: Union[str, None] = '2a529c141db6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('is_blocked', sa.Boolean(), nullable=True))

    op.execute("UPDATE posts SET is_blocked = FALSE WHERE is_blocked IS NULL")

    op.alter_column('posts', 'is_blocked', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'is_blocked')
    # ### end Alembic commands ###
