"""added auto_reply_enabled и reply_delay_minutes

Revision ID: 9e99216b39c5
Revises: d2751b6decc9
Create Date: 2024-10-21 19:22:22.107107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e99216b39c5'
down_revision: Union[str, None] = 'd2751b6decc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('parent_comment_id', sa.Integer(), nullable=True))
    op.create_foreign_key("fk_parent_comment", 'comments', 'comments', ['parent_comment_id'], ['id'])
    op.add_column('users', sa.Column('auto_reply_enabled', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('reply_delay_minutes', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reply_delay_minutes')
    op.drop_column('users', 'auto_reply_enabled')
    op.drop_constraint("fk_parent_comment", 'comments', type_='foreignkey')
    op.drop_column('comments', 'parent_comment_id')
    # ### end Alembic commands ###
