name: CI/CD

on:
  workflow_dispatch:

  push:
    branches:
      - dev
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    environment: STARNAVI

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies and run flake8
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          flake8 .

      - name: Run tests
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          SECRET_KEY_JWT: ${{ secrets.SECRET_KEY_JWT }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          TOKEN_AUTH: ${{ secrets.TOKEN_AUTH }}
        run: |
          source venv/bin/activate
          echo "DATABASE_URL: $DATABASE_URL"
          echo "POSTGRES_DB: $POSTGRES_DB"
          echo "POSTGRES_USER: $POSTGRES_USER"
          pytest