name: CI/CD

on:
  workflow_dispatch:

  push:
    branches:
      - dev
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies and run flake8
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          flake8 .

      - name: Run tests
        env:
          DATABASE_URL: postgres://user:password@localhost:5432/dbname
          POSTGRES_DB: dbname
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          SECRET_KEY_JWT: secret-key-jwt123456
          GOOGLE_APPLICATION_CREDENTIALS: ./credentials.json
          TOKEN_AUTH: test123456
        run: |
          source venv/bin/activate
          pytest